// src/components/help/content/theory.js
export const theoryContent = `
<h1>La théorie derrière Argumentor</h1>

<p>C’est en fac à l’Université d’Oslo que j’ai rencontré le sujet. Il m’est resté de l’époque un livre, <span style="font-style:italic;">Språk og argumentasjon</span> (« Langage et argumentation »), de Olav Asheim, Kolbein Brede et Bjørn Thommessen, et qui est une introduction à la linguistique, à la logique et à l’argumentation. Comme c’est Olav Asheim que j’ai eu comme professeur, on me pardonnera de ne me référer qu’à lui par la suite.</p>
<h4>Argumentation descriptive et argumentation normative</h4>
<p>Asheim défini deux types d’argumentaires : les argumentaires descriptifs et les argumentaires normatifs. Un argumentaire descriptif où l’enjeu est vrai ou faux, et un argumentaire normatif où l’enjeu est bien ou mal, ou, a minima, souhaitable ou non souhaitable. On a envie d’ajouter un autre type d’argumentaire : beau/laid. Ça viendra peut-être.</p>
<p>Et encore un, où il s’agirait de savoir quelle est la définition de quelque chose. Ça viendra peut-être aussi.</p>
<p>Asheim parle de <span style="font-style:italic;">Spissformulering</span> pour parler de l’affirmation par rapport à laquelle il s’agit de prendre position ; nous, ici, nous parlerons de la Thèse. Laquelle thèse est, donc, soit descriptive soit normative. A l’appui ou à l’encontre de la thèse on a des arguments principaux. Qui eux-mêmes sont soutenus ou contrés par d’autres arguments ; et ainsi de suite pour former toute une ramification.</p>
<h4>Codage</h4>
<p>Les arguments sont notés afin de rendre compte d’où ils se situent dans la ramification. Le premier argument principal Pour est noté P1, le deuxième P2, le troisième P3 et ainsi de suite. De la même façon, des arguments contre sont notés C1, C2, C3 et ainsi de suite. Un premier argument à l’appui de P2 sera noté p2P1, et un argument contre cet argument sera noté p2p1C1. Vous l’aurez compris, le terme le plus à gauche représente un argument principal et celui le plus à droite, en majuscule, l’argument courant*.</p>
<h4>La validité ét la pertinence d'un argument</h4>
<p>Selon Asheim, pour qu’un argument, soit un bon argument, il faut qu’il ait de la validité et de la pertinence. Ce sont deux notions qui n’ont pas la même signification selon qu’ils s’appliquent à des argumentaires descriptifs ou normatifs.</p>
<p>Dans un argument descriptif, la validité est tout simplement la validité de ce qui est affirmé. Si on soutient que la planète Vénus est couverte d’océans et qu’on avance comme argument que c’est ce qu’on prouvé les sondes soviétiques, l’argument est mauvais parce que ce n’est pas vrai que ces sondes ont découvert ça ; c’est même plutôt le contraire. </p>
<p>La pertinence est de savoir si un argument A qui soutient une thèse T est vrai, dans quelle mesure cette thèse est nécessairement vraie aussi. Toujours au sujet des océans sur la planète Vénus, un argument pour pourrait être qu’un éminent astronome, Isaac Asimov, a écrit des romans où sont décrits les océans de Vénus. L’argument est valide, puisqu’il est exact qu’Isaac Asimov était un éminent astronome, et qu’il est également exact qu’il a écrit des romans où Vénus était décrire comme couverte d’océans. Mais ce n’est pas parce qu’il a eu des romans qui décrivent la planète ainsi, quand bien même le romancier ait été un éminent astronome, que cette réalité est vraie. Quand un argument nous semble peu pertinent, on a volontiers envie de répondre : « et alors ? quel est le rapport avec le sujet ? »</p>
<p>Un bon argument a donc et de la validité et de la pertinence, et vient à l’appui soit de la validité, soit de la pertinence de son argument parent ou de la thèse.</p>
<h4>Validité et pertinence dans un argumentaire normatif</h4>
<p>Dans un argumentaire normatif, on raisonne en termes de conséquence si l’injonction était suivie d’effet. La pertinence consiste à mettre en regard l’adéquation de l’argument avec des principes ou une morale, ou la valeur positive ou négative de ces conséquences. Si on discute de l’opportunité de tenter de coloniser la planète Mars, un argument Contre serait le risque, voire la certitude, de voir des pertes humaines dans l’aventure. Ce qui est, évidemment, connoté de façon négative. Un argument Pour pourrait être de soulever le besoin irrépressible de l’humain à aller toujours plus loin.</p>
<p>La validité d’un argument consiste à évaluer la probabilité que cette conséquence se réalise effectivement. Des hommes et des femmes vont mourir dans une tentative de colonisation de la planète Mars … est-ce que c’est vrai ? Un argument dérivé d’une thèse normative devient ainsi descriptif, puisqu’on se demande si telle chose est vraie ou fausse. On revient alors à une argumentation descriptive.</p>
<p>On peut imaginer le contraire aussi, une thèse descriptive qui sur une branche devienne normative. Mais cela revient à dire que telle chose est fausse parce que si c’était vrai, ce serait immoral. Pour prendre un exemple extrême, les théories de Lyssenko étaient considérées dans l’URSS stalinienne comme vraies car communistes ; et toute génétique alternative comme fausses parce que bourgeoises. C’est clairement une faute d’argumentation mais on ne peut que noter que dans le débat public cela est très courant.</p>
<p style="font-size:small">* En réalité, Asheim fait le contraire : le terme le plus à droite représente l’argument principal et celui le plus à gauche, en majuscule, l’argument courant. Je n’ai jamais dit que Asheim était mon gourou.</p>

<h4>La quantification des arguments</h4>
<p>Argumentor propose un système de notation pour évaluer quantitativement la solidité d’un argumentaire. Ce système repose sur quatre grandeurs pour chaque argument : la <strong>valeur</strong>, la <strong>validité</strong>, la <strong>pertinence</strong> et le <strong>poids</strong>.</p>
<p>La <strong>valeur</strong> (abrégé <em>val.</em>) est la seule grandeur que vous fixez directement, de 0,0 à 1,0. Elle représente votre évaluation personnelle de la force de l’argument — indépendamment de ses sous-arguments. La valeur par défaut est 0,5 (neutre). Elle est la grandeur qui se propage vers le haut : c’est elle, et elle seule, qui contribue au score de l’argument parent.</p>
<p>La <strong>validité</strong> (V) et la <strong>pertinence</strong> (R) d’un argument sont calculées automatiquement à partir de ses enfants directs. Pour chaque enfant positionné (Pour ou Contre), sa valeur vient s’ajouter (Pour) ou se soustraire (Contre) à la dimension correspondante du parent — validité si l’enfant est un argument de validité, pertinence s’il est un argument de pertinence. Ces deux grandeurs peuvent donc être négatives si les arguments-contre l’emportent.</p>
<p>Le <strong>poids</strong> (W) est la combinaison de la validité et de la pertinence. Il est exprimé sous la forme d’une courbe en S (fonction tangente hyperbolique) : les premiers arguments qui soutiennent ont beaucoup d’impact, mais les suivants en ont de moins en moins — on approche des asymptotes +1,0 et −1,0 sans jamais les atteindre. Pour un argument sans enfants positionnés (une "feuille"), il n’y a pas de V ni de R à combiner : le poids prend alors directement la valeur que vous lui avez fixée (entre 0,0 et 1,0).</p>
<p>Enfin, le <strong>score global</strong> de l’argumentaire agrège le poids de tous les arguments (pondéré par leur position dans la thèse — pour ou contre) avec la même logique de courbe en S, mais exprimé sur une échelle de −10,0 à +10,0. Un score de 0 signifie que les arguments pour et contre s’équilibrent parfaitement ; un score proche de +10 ou −10 indique un argumentaire très fortement penché d’un côté.</p>
<p style="font-size:small">Note : le poids d’un argument ne se propage pas vers le parent. Seule la valeur se propage. Le poids est un indicateur de la solidité interne de l’argument, pas un mécanisme de transmission.</p>
`;

